---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: timestamp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: timestamp-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
